### ISSUE TITLE
Do not DELETE develop branch

### ISSUE THREAD

**Issue by el-j** [fritzing/fzp-js#6]
there is a dependency issue when trying to install fzz-js. 
the main issue comes from the fritzing-js repository, it requires

```
   "fzp-js": "fritzing/fzp-js#develop",
    "fzz-js": "fritzing/fzz-js#develop",
```
https://github.com/fritzing/fritzing-js/blob/master/package.json

for me the simplest way was to create the develop branch from the master..
the question is, if develop branches should be in a package.json,
i think the best would getting the master and keep the master clean an working.

**Comment by paulvollmer** [comment]
we should remove the `#develop` from the `package.json`
